const clientes = [
    {id: 1,
        dni: 4555555,
        nombre: "Matias",
        apellido: "Mass",
        fecha: "19/10/1995",
        telefono: "55-555-55",
        direccion: "Zacarias  Sanchez 55",
        correo: "Correo@gmail.com",
        tipoCliente: "Propietario",
        estado: "activo"
    },
    {id: 2,
        dni: 4555555,
        nombre: "Christian",
        apellido: "Gomez",
        fecha: "19/10/1995",
        telefono: "55-555-55",
        direccion: "Zacarias  Sanchez 55",
        correo: "Correo@gmail.com",
        tipoCliente: "Propietario",
        estado: "activo"   
    },
    {id: 3,
        dni: 4555555,
        nombre: "Thomas",
        apellido: "Ojeda",  
        fecha: "19/10/1995",
        telefono: "55-555-55",
        direccion: "Zacarias  Sanchez 55",
        correo: "Correo@gmail.com",
        tipoCliente: "Propietario",
        estado: "activo"
    },
    {id: 4,
        dni: 4555555,
        nombre: "Facuando",
        apellido: "Barboza",  
        fecha: "19/10/1995",
        telefono: "55-555-55",
        direccion: "Zacarias  Sanchez 55",
        correo: "Correo@gmail.com",
        tipoCliente: "Propietario",
        estado: "activo"
    },
    {id: 5,
        dni: 4555555,
        nombre: "Joaquin",
        apellido: "Desza",
        fecha: "19/10/1995",
        telefono: "55-555-55",
        direccion: "Zacarias  Sanchez 55",
        correo: "Correo@gmail.com",
        tipoCliente: "Propietario",
        estado: "activo"
    },
    {id: 6,
        dni: 4555555,
        nombre: "Joaquin",
        apellido: "De los Reyes",
        fecha: "19/10/1995",
        telefono: "55-555-55",
        direccion: "Zacarias  Sanchez 55",
        correo: "Correo@gmail.com",
        tipoCliente: "Propietario",
        estado: "activo"
    },
    {id: 7,
        dni: 4555555,
        nombre: "Brad",
        apellido: "Pitt",
        fecha: "19/10/1995",
        telefono: "55-555-55",
        direccion: "Zacarias  Sanchez 55",
        correo: "Correo@gmail.com",
        tipoCliente: "Propietario",
        estado: "activo"
    },
    {id: 8,
        dni: 4555555,
        nombre: "Keanu",
        apellido: "Reves",
        fecha: "19/10/1995",
        telefono: "55-555-55",
        direccion: "Zacarias  Sanchez 55",
        correo: "Correo@gmail.com",
        tipoCliente: "Propietario",
        estado: "activo"
    },
]

export default clientes